[package]
name = "j1939-stats"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stats"
path = "src/run.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
canparse = { version="0.1", features=["use-socketcan"] }
socketcan = "1.7"
sled = "0.34"
